--- 

- name: nginx | Install nginx
  apt:
    name: nginx
    state: latest

- name: nginx | install letsencrypt
  apt:
    name: letsencrypt
    state: latest

- name: nginx | create letsencrypt directory
  file:
    name: /var/www/letsencrypt
    state: directory

- name: nginx | Remove default nginx config
  file: 
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: nginx | Install system nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: nginx | Install nginx site for letsencrypt requests
  template:
    src: nginx-http.j2
    dest: /etc/nginx/sites-enabled/http

- name: nginx | Reload nginx to activate letsencrypt site
  service:
    name: nginx
    state: restarted

- name: nginx | Create letsencrypt combined certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ nginx_letsencrypt_email }} --agree-tos -d "{{ nginx_hosts | map(attribute='domain_name') | join(',')  }}" --renew-with-new-domains --cert-name "{{ nginx_hosts | map(attribute='domain_name') | first }}"
  when: nginx_single_cert

- name: nginx | Create letsencrypt standalone certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ nginx_letsencrypt_email }} --agree-tos -d "{{ item }}" --cert-name "{{ nginx_hosts | map(attribute='domain_name') }}"
  loop: "{{ nginx_hosts | map(attribute='domain_name') }}"
  when: not nginx_single_cert

- name: nginx | Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: nginx | Install nginx site for specified site
  template:
    src: nginx-le.j2
    dest: /etc/nginx/sites-enabled/le

- name: nginx | Reload nginx to activate specified site
  service: name=nginx state=restarted
- name: Add letsencrypt cronjob for combined cert renewal
  cron:
   name: letsencrypt_renewal
   special_time: weekly
   job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ nginx_letsencrypt_email }} --agree-tos -d "{{ nginx_hosts | map(attribute='domain_name') | join(',') }}" && service nginx reload
  when: nginx_single_cert

- name: nginx | Add letsencrypt cronjob for standalone cert renewal
  cron:
   name: letsencrypt_renewal
   special_time: weekly
   job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ nginx_letsencrypt_email }} --agree-tos -d "{{ domain_name }}" && service nginx reload
  loop: "{{ nginx_hosts | map(attribute='domain_name') }}"
  when: not nginx_single_cert

- name: nginx | install users file
  template:
    src: users.j2
    dest: /etc/nginx/{{item.domain_name}}.htpasswd
  loop: "{{ nginx_hosts|selectattr('users','defined') }}"
  when: nginx_hosts|selectattr('users','defined')
